---
# tasks file for copy_file
- name: copiando un fichero
  copy:
    src: /etc/hosts
    dest: /tmp/{{ nombre_fichero }}

# Automating updates for Debian systems.
- name: Install unattended upgrades package.
  apt:
    name: unattended-upgrades
    state: present
  when: ansible_os_family == 'Debian'

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
  when: ansible_os_family == 'Debian'

# Configuring a firewall with `firewalld` on RHEL.
- name: Ensure firewalld is running.
  service:
    name: firewalld
    state: started

- name: Configure open ports with firewalld.
  firewalld:
    state: "{{ item.state }}"
    port: "{{ item.port }}"
    zone: external
    immediate: yes
    permanent: yes
  with_items:
    - { state: 'enabled', port: '22/tcp' }
    - { state: 'enabled', port: '80/tcp' }
    - { state: 'enabled', port: '123/udp' }